### ISSUE TITLE
Error in transreg subset argument

### ISSUE THREAD

**Issue by yushuf** [ekenah/transtat#1]
t <- transreg(
  Surv(interval, infector) ~ infx + susx + ext(external),
  sus = "susceptible", data = dat, subset= trace !=0, 
  dist = "exponential", xdist = "exponential"
)
command produce the following error

Error in `$<-.data.frame`(`*tmp*`, "sus", value = c(1382L, 256L, 263L,  : 
  replacement has 3752 rows, data has 2992

but subsetting in different way works e.g.

t <- transreg(
  Surv(interval, infector) ~ infx + susx + ext(external),
  sus = "susceptible", data = dat[dat$trace!=0,], 
  dist = "exponential", xdist = "exponential"
)

**Comment by ekenah** [comment]
The subset argument was not handled properly when 'sus' was added to the 'ymat' matrix of responses. This has been fixed in version 0.2.1.
