### ISSUE TITLE
Error: transreg confing with LR option

### ISSUE THREAD

**Issue by yushuf** [ekenah/transtat#4]
Still sometimes the following error appears.

Error in uniroot(parm_d, treg$coefficients[parm] + c(-1.25, -0.75) * z *  :
  no sign change found in 1000 iterations
Calls: write.csv ... confint.transreg -> sapply -> lapply -> FUN -> uniroot
Execution halted

**Comment by ekenah** [comment]
Please attach data files for which the error occurred so I can replicate it. How often does this error occur?

**Comment by yushuf** [comment]
here is the data files. difficult to say how frequently it is happening.
This appeared in my third test on hypergator. That means in 8th iteration
that appeared.

Thanks

**Comment by ekenah** [comment]
I don't know what "8th iteration" means. I am looking for an answer like "This happened three times in five hundred simulations."

I also don't see the data files.

**Comment by ekenah** [comment]
It looks like the problem occurs when the model tries to calculate likelihood ratio confidence intervals for a model in which there is a very small number of internal infections in one of the four possible covariate combinations. This is not a transreg error; it is a limitation of the likelihood itself.
